security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        vr_device_provider:
            entity:
                class: App\Entity\VrDevice
                property: identifier

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: vr_device_provider
            jwt: ~
        admin:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: dashboard
                username_parameter: login_form[email]
                password_parameter: login_form[password]
                enable_csrf: true
            logout:
                path: admin_logout
                target: admin_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

    access_control:
        - { path: ^/api/v1/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_VR_DEVICE }
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: [ROLE_TENANT_USER, ROLE_TENANT_ADMIN, ROLE_SUPER_ADMIN] }
